const pages=document.querySelectorAll('.page');const navs=document.querySelectorAll('.nav');
function showPage(id){pages.forEach(p=>p.classList.toggle('active-page',p.id===id));navs.forEach(n=>n.classList.toggle('active',n.dataset.page===id));const titles={dashboard:'Good morning, Ebad 👋',body:'AI Body Analysis',plans:'My Fitness Plans',tracker:'Habit Tracker',chat:'AI Fitness Coach',progress:'Progress Tracking',admin:'Admin Dashboard'};document.getElementById('pageTitle').textContent=titles[id]||'FitAI';window.scrollTo({top:0,behavior:'smooth'})}
navs.forEach(n=>n.addEventListener('click',()=>showPage(n.dataset.page)));
document.querySelectorAll('.upload-box').forEach(box=>{const input=box.querySelector('input');input.addEventListener('change',()=>{if(input.files[0]){box.querySelector('.upload-icon').textContent='✅';box.querySelector('p').textContent=input.files[0].name;toast(box.dataset.slot+' photo uploaded')}})});
function selectGoal(el){document.querySelectorAll('.goal').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')}
function generatePlan(){toast('AI plan generated successfully!');}
function updateHabits(){const checks=[...document.querySelectorAll('.habit-list input')];const done=checks.filter(x=>x.checked).length;const pct=Math.round(done/checks.length*100);document.getElementById('completion').textContent=pct+'%';document.getElementById('progressBar').style.width=pct+'%';toast('Habit progress updated');}
function sendChat(){const input=document.getElementById('chatInput');const text=input.value.trim();if(!text)return;const box=document.getElementById('messages');box.insertAdjacentHTML('beforeend',`<div class="message user">${escapeHtml(text)}</div>`);let reply='Stay consistent with your plan, drink enough water and give your body time to recover. 💪';if(/protein|eat|food|meal/i.test(text))reply='For your goal, choose a balanced meal with protein, vegetables and a suitable portion of carbs. 🥗';if(/workout|exercise|gym/i.test(text))reply='Try your scheduled workout and focus on correct form. Warm up first and stop if you feel pain. 🏋️';box.insertAdjacentHTML('beforeend',`<div class="message ai">${reply}</div>`);input.value='';box.scrollTop=box.scrollHeight}
document.getElementById('chatInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendChat()});
function filterUsers(q){document.querySelectorAll('#users tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q.toLowerCase())?'':'none')}
function ban(btn){btn.closest('tr').querySelector('.status').textContent='Banned';btn.closest('tr').querySelector('.status').style.color='#b91c1c';btn.closest('tr').querySelector('.status').style.background='#fee2e2';btn.textContent='Unban';toast('User status changed')}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.style.display='block';clearTimeout(window.tt);window.tt=setTimeout(()=>t.style.display='none',2200)}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}